### ISSUE TITLE
SSL handshake

### ISSUE THREAD

**Issue by Maievmau** [ActiveAgeingHKR/MainServerREST#3]
Guy, this could be only my PC. But when i pulled today i got this error message on the Proxy Server:
After consulting with Karolis, it seems to be a problem with connecting to the Main Server.

`Waiting for client at port:12345
deviceID: N867BY2FW5
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at mainserver.Server.getCustomerID(Server.java:160)
	at mainserver.ProxyThread.run(ProxyThread.java:31)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 22 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 28 more
`
Don't kill me. X'D

**Comment by Maievmau** [comment]
Forgot to mention that GlassFish spams this:

`Info:   Loading application [MainServerREST] at [/MainServerREST]
Info:   MainServerREST was successfully deployed in 2,415 milliseconds.
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/devicescustomers/N867BY2FW5" "GET"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/devicescustomers/N867BY2FW5" "GET"))
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/incidents/isalive" "POST"))`

N867BY2FW5 is the serial number of the smartwatch.

Oooor, this is the Proxy Server issue again since they haven't implemented SSL? XD Or?

**Comment by chrissexton017** [comment]
Hello Marija,

This is definitely SSL-related. It is actually the precise error that I used to get if I tried to connect to the Main Server from the JavaFX application without using the SSL library that @Bitharis developed. However, if I use @Bitharis library in the JavaFX application, this error no longer occurs.

@Bitharis  is perhaps the best person to explain the whys and hows of this, since he has done the most work on the SSL feature generally and I am not familiar with exactly how his SSL connector library works (I am still studying it as we speak) but it certainly seems to work and do the job it is intended for. 

So I believe that this is a MainServer issue only in the sense that it relates to SSL, but that the implementation of the SSL connector library on the Proxy (if that has not been done yet) is probably the solution to it. But @Bitharis may correct me.

**Comment by Bitharis** [comment]
Hello,
Regarding the first message, it happens because the certificate is self signed and the Proxy cannot find the authority inside the trusted CA's, therefore it drops the certificate received by the MainServerREST.
This is not a problem from the MainServerREST side. It has to be treated from the ProxyServer side. 
They could use the SSLConnector to bypass the problem like the Units team did. 
Regarding the info from glassfish they are not SSL related.

**Comment by Maievmau** [comment]
What is the GlassFish part then? Is it something i can fix?

**Comment by Bitharis** [comment]
If you pulled the last version of MainServerREST and you have configures ADMIN and EMPLOYEE correctly then you are ok.

**Comment by swashyson** [comment]
There are some steps i posted on the forums you can follow

**Comment by Maievmau** [comment]
I do have ADMIN and EMPLOYEE. If it's those steps, yeah, done a long time ago.
But i can double check since i did make some changes to GlassFish.

**Comment by Maievmau** [comment]
![glassfish](https://cloud.githubusercontent.com/assets/17614378/21711737/d0f5811a-d3f0-11e6-987a-8481fd83e0df.PNG)

**Comment by Bitharis** [comment]
yeap seems OK

**Comment by Maievmau** [comment]
And it is of course GlassFish 4.1 and not 4.1.1, so i've no idea what it could be.

**Comment by chrissexton017** [comment]
Hey Marija,

Sorry if this is a dumb question but have you assigned these users to the relevant group on your Glassfish server too? The "EMPLOYEE" user must be in a group called "Employees" and the "ADMIN" in a group called "Managers". This is because the "roles" defined in the application need to map to "groups" on the Glassfish admin side. Mattias has defined those in the glassfish-web.xml here:

![image](https://cloud.githubusercontent.com/assets/18405480/21714119/a59f374c-d3fd-11e6-87ff-ffea061cacda.png)

...but you probably already did this in which case just ignore me.

**Comment by Maievmau** [comment]
Not dumb at all. I've absolutely missed that somehow. XD Thanks!

**Comment by chrissexton017** [comment]
Ok cool, mine looks like this in Glassfish, and this allows me to use the JavaFX application properly:

![image](https://cloud.githubusercontent.com/assets/18405480/21716181/29527904-d409-11e6-886c-86035e2d43ed.png)

**Comment by Maievmau** [comment]
JavaFX worked for me even without this. XD I'll re-test to see what's happening now (and i also know how to solve some problems Rolandas had because i guided him through this.)

P.S. I will just wait for the Proxy server's new SSL commit before i close this issue (in case i run into some more trouble, but highly unlikely).
Thanks again, Chris! :)
